### ISSUE TITLE
Adding Hashtags / pics

### ISSUE THREAD

**Issue by johnpatkinson** [dasdom/Poster#8]
Dominik
When adding hashtags it automatically adds a space between the hashtag and the wording. 
![poster](https://cloud.githubusercontent.com/assets/5547278/8589642/69d6fa34-2610-11e5-9eac-399ae312c35c.jpg)
Also when adding a picture it makes it square as in Instagram square will this be fixed in the future as this is the first app i have seen do this.

**Comment by dasdom** [comment]
Thanks! I'll fix both hopefully this weekend.

**Comment by johnpatkinson** [comment]
Thanks Dominik :)

**Comment by dasdom** [comment]
Could you please check again the hashtag issue? Because I can't reproduce it.

**Comment by dasdom** [comment]
Should be fixed in version 0.4
